//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Address
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Address()
    {
        this.BusinessEntityAddresses = new HashSet<BusinessEntityAddress>();
        this.SalesOrderHeaders = new HashSet<SalesOrderHeader>();
        this.SalesOrderHeaders1 = new HashSet<SalesOrderHeader>();
    }

    public int AddressID { get; set; }
    public string AddressLine1 { get; set; }
    public string AddressLine2 { get; set; }
    public string City { get; set; }
    public int StateProvinceID { get; set; }
    public string PostalCode { get; set; }
    //public System.Data.Entity.Spatial.DbGeography SpatialLocation { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual StateProvince StateProvince { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BusinessEntityAddress> BusinessEntityAddresses { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders1 { get; set; }
}

public partial class AddressType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AddressType()
    {
        this.BusinessEntityAddresses = new HashSet<BusinessEntityAddress>();
    }

    public int AddressTypeID { get; set; }
    public string Name { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BusinessEntityAddress> BusinessEntityAddresses { get; set; }
}

public partial class AWBuildVersion
{
    public byte SystemInformationID { get; set; }
    public string Database_Version { get; set; }
    public System.DateTime VersionDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }
}

public partial class BillOfMaterial
{
    public int BillOfMaterialsID { get; set; }
    public Nullable<int> ProductAssemblyID { get; set; }
    public int ComponentID { get; set; }
    public System.DateTime StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public string UnitMeasureCode { get; set; }
    public short BOMLevel { get; set; }
    public decimal PerAssemblyQty { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
    public virtual Product Product1 { get; set; }
    public virtual UnitMeasure UnitMeasure { get; set; }
}

public partial class BusinessEntity
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public BusinessEntity()
    {
        this.BusinessEntityAddresses = new HashSet<BusinessEntityAddress>();
        this.BusinessEntityContacts = new HashSet<BusinessEntityContact>();
    }

    public int BusinessEntityID { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BusinessEntityAddress> BusinessEntityAddresses { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BusinessEntityContact> BusinessEntityContacts { get; set; }
    public virtual Person Person { get; set; }
    public virtual Store Store { get; set; }
    public virtual Vendor Vendor { get; set; }
}

public partial class BusinessEntityAddress
{
    public int BusinessEntityID { get; set; }
    public int AddressID { get; set; }
    public int AddressTypeID { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Address Address { get; set; }
    public virtual AddressType AddressType { get; set; }
    public virtual BusinessEntity BusinessEntity { get; set; }
}

public partial class BusinessEntityContact
{
    public int BusinessEntityID { get; set; }
    public int PersonID { get; set; }
    public int ContactTypeID { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual BusinessEntity BusinessEntity { get; set; }
    public virtual ContactType ContactType { get; set; }
    public virtual Person Person { get; set; }
}

public partial class ContactType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ContactType()
    {
        this.BusinessEntityContacts = new HashSet<BusinessEntityContact>();
    }

    public int ContactTypeID { get; set; }
    public string Name { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BusinessEntityContact> BusinessEntityContacts { get; set; }
}

public partial class CountryRegion
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CountryRegion()
    {
        this.CountryRegionCurrencies = new HashSet<CountryRegionCurrency>();
        this.SalesTerritories = new HashSet<SalesTerritory>();
        this.StateProvinces = new HashSet<StateProvince>();
    }

    public string CountryRegionCode { get; set; }
    public string Name { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CountryRegionCurrency> CountryRegionCurrencies { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesTerritory> SalesTerritories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<StateProvince> StateProvinces { get; set; }
}

public partial class CountryRegionCurrency
{
    public string CountryRegionCode { get; set; }
    public string CurrencyCode { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual CountryRegion CountryRegion { get; set; }
    public virtual Currency Currency { get; set; }
}

public partial class CreditCard
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CreditCard()
    {
        this.PersonCreditCards = new HashSet<PersonCreditCard>();
        this.SalesOrderHeaders = new HashSet<SalesOrderHeader>();
    }

    public int CreditCardID { get; set; }
    public string CardType { get; set; }
    public string CardNumber { get; set; }
    public byte ExpMonth { get; set; }
    public short ExpYear { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PersonCreditCard> PersonCreditCards { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
}

public partial class Culture
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Culture()
    {
        this.ProductModelProductDescriptionCultures = new HashSet<ProductModelProductDescriptionCulture>();
    }

    public string CultureID { get; set; }
    public string Name { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCultures { get; set; }
}

public partial class Currency
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Currency()
    {
        this.CountryRegionCurrencies = new HashSet<CountryRegionCurrency>();
        this.CurrencyRates = new HashSet<CurrencyRate>();
        this.CurrencyRates1 = new HashSet<CurrencyRate>();
    }

    public string CurrencyCode { get; set; }
    public string Name { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CountryRegionCurrency> CountryRegionCurrencies { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CurrencyRate> CurrencyRates { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CurrencyRate> CurrencyRates1 { get; set; }
}

public partial class CurrencyRate
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public CurrencyRate()
    {
        this.SalesOrderHeaders = new HashSet<SalesOrderHeader>();
    }

    public int CurrencyRateID { get; set; }
    public System.DateTime CurrencyRateDate { get; set; }
    public string FromCurrencyCode { get; set; }
    public string ToCurrencyCode { get; set; }
    public decimal AverageRate { get; set; }
    public decimal EndOfDayRate { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Currency Currency { get; set; }
    public virtual Currency Currency1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
}

public partial class Customer
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customer()
    {
        this.SalesOrderHeaders = new HashSet<SalesOrderHeader>();
    }

    public int CustomerID { get; set; }
    public Nullable<int> PersonID { get; set; }
    public Nullable<int> StoreID { get; set; }
    public Nullable<int> TerritoryID { get; set; }
    public string AccountNumber { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Person Person { get; set; }
    public virtual SalesTerritory SalesTerritory { get; set; }
    public virtual Store Store { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
}

public partial class CustomerPII
{
    public int CustomerID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string SSN { get; set; }
    public string CreditCardNumber { get; set; }
    public string EmailAddress { get; set; }
    public string PhoneNumber { get; set; }
    public Nullable<int> TerritoryID { get; set; }
}

public partial class DatabaseLog
{
    public int DatabaseLogID { get; set; }
    public System.DateTime PostTime { get; set; }
    public string DatabaseUser { get; set; }
    public string Event { get; set; }
    public string Schema { get; set; }
    public string Object { get; set; }
    public string TSQL { get; set; }
    public string XmlEvent { get; set; }
}

public partial class DemoSalesOrderDetailSeed
{
    public short OrderQty { get; set; }
    public int ProductID { get; set; }
    public int SpecialOfferID { get; set; }
    public int OrderID { get; set; }
    public int LocalID { get; set; }
}

public partial class DemoSalesOrderHeaderSeed
{
    public System.DateTime DueDate { get; set; }
    public int CustomerID { get; set; }
    public int SalesPersonID { get; set; }
    public int BillToAddressID { get; set; }
    public int ShipToAddressID { get; set; }
    public int ShipMethodID { get; set; }
    public int LocalID { get; set; }
}

public partial class Department
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {
        this.EmployeeDepartmentHistories = new HashSet<EmployeeDepartmentHistory>();
    }

    public short DepartmentID { get; set; }
    public string Name { get; set; }
    public string GroupName { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeeDepartmentHistory> EmployeeDepartmentHistories { get; set; }
}

public partial class EmailAddress
{
    public int BusinessEntityID { get; set; }
    public int EmailAddressID { get; set; }
    public string EmailAddress1 { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Person Person { get; set; }
}

public partial class Employee
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Employee()
    {
        this.EmployeeDepartmentHistories = new HashSet<EmployeeDepartmentHistory>();
        this.EmployeePayHistories = new HashSet<EmployeePayHistory>();
        this.JobCandidates = new HashSet<JobCandidate>();
        this.PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
    }

    public int BusinessEntityID { get; set; }
    public string NationalIDNumber { get; set; }
    public string LoginID { get; set; }
    public Nullable<short> OrganizationLevel { get; set; }
    public string JobTitle { get; set; }
    public System.DateTime BirthDate { get; set; }
    public string MaritalStatus { get; set; }
    public string Gender { get; set; }
    public System.DateTime HireDate { get; set; }
    public bool SalariedFlag { get; set; }
    public short VacationHours { get; set; }
    public short SickLeaveHours { get; set; }
    public bool CurrentFlag { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Person Person { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeeDepartmentHistory> EmployeeDepartmentHistories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeePayHistory> EmployeePayHistories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<JobCandidate> JobCandidates { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
    public virtual SalesPerson SalesPerson { get; set; }
}

public partial class Employee_Temporal
{
    public int BusinessEntityID { get; set; }
    public string NationalIDNumber { get; set; }
    public string LoginID { get; set; }
    public Nullable<short> OrganizationLevel { get; set; }
    public string JobTitle { get; set; }
    public System.DateTime BirthDate { get; set; }
    public string MaritalStatus { get; set; }
    public string Gender { get; set; }
    public System.DateTime HireDate { get; set; }
    public short VacationHours { get; set; }
    public short SickLeaveHours { get; set; }
    public System.DateTime ValidFrom { get; set; }
    public System.DateTime ValidTo { get; set; }
}

public partial class Employee_Temporal_History
{
    public int BusinessEntityID { get; set; }
    public string NationalIDNumber { get; set; }
    public string LoginID { get; set; }
    public Nullable<short> OrganizationLevel { get; set; }
    public string JobTitle { get; set; }
    public System.DateTime BirthDate { get; set; }
    public string MaritalStatus { get; set; }
    public string Gender { get; set; }
    public System.DateTime HireDate { get; set; }
    public short VacationHours { get; set; }
    public short SickLeaveHours { get; set; }
    public System.DateTime ValidFrom { get; set; }
    public System.DateTime ValidTo { get; set; }
}

public partial class EmployeeDepartmentHistory
{
    public int BusinessEntityID { get; set; }
    public short DepartmentID { get; set; }
    public byte ShiftID { get; set; }
    public System.DateTime StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Department Department { get; set; }
    public virtual Employee Employee { get; set; }
    public virtual Shift Shift { get; set; }
}

public partial class EmployeePayHistory
{
    public int BusinessEntityID { get; set; }
    public System.DateTime RateChangeDate { get; set; }
    public decimal Rate { get; set; }
    public byte PayFrequency { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Employee Employee { get; set; }
}

public partial class ErrorLog
{
    public int ErrorLogID { get; set; }
    public System.DateTime ErrorTime { get; set; }
    public string UserName { get; set; }
    public int ErrorNumber { get; set; }
    public Nullable<int> ErrorSeverity { get; set; }
    public Nullable<int> ErrorState { get; set; }
    public string ErrorProcedure { get; set; }
    public Nullable<int> ErrorLine { get; set; }
    public string ErrorMessage { get; set; }
}

public partial class Illustration
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Illustration()
    {
        this.ProductModelIllustrations = new HashSet<ProductModelIllustration>();
    }

    public int IllustrationID { get; set; }
    public string Diagram { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductModelIllustration> ProductModelIllustrations { get; set; }
}

public partial class JobCandidate
{
    public int JobCandidateID { get; set; }
    public Nullable<int> BusinessEntityID { get; set; }
    public string Resume { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Employee Employee { get; set; }
}

public partial class Location
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Location()
    {
        this.ProductInventories = new HashSet<ProductInventory>();
        this.WorkOrderRoutings = new HashSet<WorkOrderRouting>();
    }

    public short LocationID { get; set; }
    public string Name { get; set; }
    public decimal CostRate { get; set; }
    public decimal Availability { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductInventory> ProductInventories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<WorkOrderRouting> WorkOrderRoutings { get; set; }
}

public partial class OrderTracking
{
    public int OrderTrackingID { get; set; }
    public int SalesOrderID { get; set; }
    public string CarrierTrackingNumber { get; set; }
    public int TrackingEventID { get; set; }
    public string EventDetails { get; set; }
    public System.DateTime EventDateTime { get; set; }
}

public partial class Password
{
    public int BusinessEntityID { get; set; }
    public string PasswordHash { get; set; }
    public string PasswordSalt { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Person Person { get; set; }
}

public partial class Person
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Person()
    {
        this.BusinessEntityContacts = new HashSet<BusinessEntityContact>();
        this.EmailAddresses = new HashSet<EmailAddress>();
        this.Customers = new HashSet<Customer>();
        this.PersonCreditCards = new HashSet<PersonCreditCard>();
        this.PersonPhones = new HashSet<PersonPhone>();
    }

    public int BusinessEntityID { get; set; }
    public string PersonType { get; set; }
    public bool NameStyle { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string MiddleName { get; set; }
    public string LastName { get; set; }
    public string Suffix { get; set; }
    public int EmailPromotion { get; set; }
    public string AdditionalContactInfo { get; set; }
    public string Demographics { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Employee Employee { get; set; }
    public virtual BusinessEntity BusinessEntity { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BusinessEntityContact> BusinessEntityContacts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmailAddress> EmailAddresses { get; set; }
    public virtual Password Password { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Customer> Customers { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PersonCreditCard> PersonCreditCards { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PersonPhone> PersonPhones { get; set; }
}

public partial class Person_json
{
    public int PersonID { get; set; }
    public string PersonType { get; set; }
    public bool NameStyle { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string MiddleName { get; set; }
    public string LastName { get; set; }
    public string Suffix { get; set; }
    public int EmailPromotion { get; set; }
    public string AdditionalContactInfo { get; set; }
    public string Demographics { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }
}

public partial class Person_Temporal
{
    public int BusinessEntityID { get; set; }
    public string PersonType { get; set; }
    public bool NameStyle { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string MiddleName { get; set; }
    public string LastName { get; set; }
    public string Suffix { get; set; }
    public int EmailPromotion { get; set; }
    public System.DateTime ValidFrom { get; set; }
    public System.DateTime ValidTo { get; set; }
}

public partial class Person_Temporal_History
{
    public int BusinessEntityID { get; set; }
    public string PersonType { get; set; }
    public bool NameStyle { get; set; }
    public string Title { get; set; }
    public string FirstName { get; set; }
    public string MiddleName { get; set; }
    public string LastName { get; set; }
    public string Suffix { get; set; }
    public int EmailPromotion { get; set; }
    public System.DateTime ValidFrom { get; set; }
    public System.DateTime ValidTo { get; set; }
}

public partial class PersonCreditCard
{
    public int BusinessEntityID { get; set; }
    public int CreditCardID { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Person Person { get; set; }
    public virtual CreditCard CreditCard { get; set; }
}

public partial class PersonPhone
{
    public int BusinessEntityID { get; set; }
    public string PhoneNumber { get; set; }
    public int PhoneNumberTypeID { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Person Person { get; set; }
    public virtual PhoneNumberType PhoneNumberType { get; set; }
}

public partial class PhoneNumberType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PhoneNumberType()
    {
        this.PersonPhones = new HashSet<PersonPhone>();
    }

    public int PhoneNumberTypeID { get; set; }
    public string Name { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PersonPhone> PersonPhones { get; set; }
}

public partial class Product
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {
        this.BillOfMaterials = new HashSet<BillOfMaterial>();
        this.BillOfMaterials1 = new HashSet<BillOfMaterial>();
        this.ProductCostHistories = new HashSet<ProductCostHistory>();
        this.ProductInventories = new HashSet<ProductInventory>();
        this.ProductListPriceHistories = new HashSet<ProductListPriceHistory>();
        this.ProductProductPhotoes = new HashSet<ProductProductPhoto>();
        this.ProductReviews = new HashSet<ProductReview>();
        this.ProductVendors = new HashSet<ProductVendor>();
        this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
        this.ShoppingCartItems = new HashSet<ShoppingCartItem>();
        this.SpecialOfferProducts = new HashSet<SpecialOfferProduct>();
        this.TransactionHistories = new HashSet<TransactionHistory>();
        this.WorkOrders = new HashSet<WorkOrder>();
    }

    public int ProductID { get; set; }
    public string Name { get; set; }
    public string ProductNumber { get; set; }
    public bool MakeFlag { get; set; }
    public bool FinishedGoodsFlag { get; set; }
    public string Color { get; set; }
    public short SafetyStockLevel { get; set; }
    public short ReorderPoint { get; set; }
    public decimal StandardCost { get; set; }
    public decimal ListPrice { get; set; }
    public string Size { get; set; }
    public string SizeUnitMeasureCode { get; set; }
    public string WeightUnitMeasureCode { get; set; }
    public Nullable<decimal> Weight { get; set; }
    public int DaysToManufacture { get; set; }
    public string ProductLine { get; set; }
    public string Class { get; set; }
    public string Style { get; set; }
    public Nullable<int> ProductSubcategoryID { get; set; }
    public Nullable<int> ProductModelID { get; set; }
    public System.DateTime SellStartDate { get; set; }
    public Nullable<System.DateTime> SellEndDate { get; set; }
    public Nullable<System.DateTime> DiscontinuedDate { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BillOfMaterial> BillOfMaterials { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BillOfMaterial> BillOfMaterials1 { get; set; }
    public virtual ProductModel ProductModel { get; set; }
    public virtual ProductSubcategory ProductSubcategory { get; set; }
    public virtual UnitMeasure UnitMeasure { get; set; }
    public virtual UnitMeasure UnitMeasure1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductCostHistory> ProductCostHistories { get; set; }
    public virtual ProductDocument ProductDocument { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductInventory> ProductInventories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductListPriceHistory> ProductListPriceHistories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductProductPhoto> ProductProductPhotoes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductReview> ProductReviews { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductVendor> ProductVendors { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ShoppingCartItem> ShoppingCartItems { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SpecialOfferProduct> SpecialOfferProducts { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<TransactionHistory> TransactionHistories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<WorkOrder> WorkOrders { get; set; }
}

public partial class Product_inmem
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product_inmem()
    {
        this.SpecialOfferProduct_inmem = new HashSet<SpecialOfferProduct_inmem>();
    }

    public int ProductID { get; set; }
    public string Name { get; set; }
    public string ProductNumber { get; set; }
    public bool MakeFlag { get; set; }
    public bool FinishedGoodsFlag { get; set; }
    public string Color { get; set; }
    public short SafetyStockLevel { get; set; }
    public short ReorderPoint { get; set; }
    public decimal StandardCost { get; set; }
    public decimal ListPrice { get; set; }
    public string Size { get; set; }
    public string SizeUnitMeasureCode { get; set; }
    public string WeightUnitMeasureCode { get; set; }
    public Nullable<decimal> Weight { get; set; }
    public int DaysToManufacture { get; set; }
    public string ProductLine { get; set; }
    public string Class { get; set; }
    public string Style { get; set; }
    public Nullable<int> ProductSubcategoryID { get; set; }
    public Nullable<int> ProductModelID { get; set; }
    public System.DateTime SellStartDate { get; set; }
    public Nullable<System.DateTime> SellEndDate { get; set; }
    public Nullable<System.DateTime> DiscontinuedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SpecialOfferProduct_inmem> SpecialOfferProduct_inmem { get; set; }
}

public partial class Product_ondisk
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product_ondisk()
    {
        this.SpecialOfferProduct_ondisk = new HashSet<SpecialOfferProduct_ondisk>();
    }

    public int ProductID { get; set; }
    public string Name { get; set; }
    public string ProductNumber { get; set; }
    public bool MakeFlag { get; set; }
    public bool FinishedGoodsFlag { get; set; }
    public string Color { get; set; }
    public short SafetyStockLevel { get; set; }
    public short ReorderPoint { get; set; }
    public decimal StandardCost { get; set; }
    public decimal ListPrice { get; set; }
    public string Size { get; set; }
    public string SizeUnitMeasureCode { get; set; }
    public string WeightUnitMeasureCode { get; set; }
    public Nullable<decimal> Weight { get; set; }
    public int DaysToManufacture { get; set; }
    public string ProductLine { get; set; }
    public string Class { get; set; }
    public string Style { get; set; }
    public Nullable<int> ProductSubcategoryID { get; set; }
    public Nullable<int> ProductModelID { get; set; }
    public System.DateTime SellStartDate { get; set; }
    public Nullable<System.DateTime> SellEndDate { get; set; }
    public Nullable<System.DateTime> DiscontinuedDate { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SpecialOfferProduct_ondisk> SpecialOfferProduct_ondisk { get; set; }
}

public partial class ProductCategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductCategory()
    {
        this.ProductSubcategories = new HashSet<ProductSubcategory>();
    }

    public int ProductCategoryID { get; set; }
    public string Name { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductSubcategory> ProductSubcategories { get; set; }
}

public partial class ProductCostHistory
{
    public int ProductID { get; set; }
    public System.DateTime StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public decimal StandardCost { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
}

public partial class ProductDescription
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductDescription()
    {
        this.ProductModelProductDescriptionCultures = new HashSet<ProductModelProductDescriptionCulture>();
    }

    public int ProductDescriptionID { get; set; }
    public string Description { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCultures { get; set; }
}

public partial class ProductDocument
{
    public int ProductID { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
}

public partial class ProductInventory
{
    public int ProductID { get; set; }
    public short LocationID { get; set; }
    public string Shelf { get; set; }
    public byte Bin { get; set; }
    public short Quantity { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Location Location { get; set; }
    public virtual Product Product { get; set; }
}

public partial class ProductListPriceHistory
{
    public int ProductID { get; set; }
    public System.DateTime StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public decimal ListPrice { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
}

public partial class ProductModel
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductModel()
    {
        this.Products = new HashSet<Product>();
        this.ProductModelIllustrations = new HashSet<ProductModelIllustration>();
        this.ProductModelProductDescriptionCultures = new HashSet<ProductModelProductDescriptionCulture>();
    }

    public int ProductModelID { get; set; }
    public string Name { get; set; }
    public string CatalogDescription { get; set; }
    public string Instructions { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductModelIllustration> ProductModelIllustrations { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductModelProductDescriptionCulture> ProductModelProductDescriptionCultures { get; set; }
}

public partial class ProductModelIllustration
{
    public int ProductModelID { get; set; }
    public int IllustrationID { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Illustration Illustration { get; set; }
    public virtual ProductModel ProductModel { get; set; }
}

public partial class ProductModelProductDescriptionCulture
{
    public int ProductModelID { get; set; }
    public int ProductDescriptionID { get; set; }
    public string CultureID { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Culture Culture { get; set; }
    public virtual ProductDescription ProductDescription { get; set; }
    public virtual ProductModel ProductModel { get; set; }
}

public partial class ProductPhoto
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductPhoto()
    {
        this.ProductProductPhotoes = new HashSet<ProductProductPhoto>();
    }

    public int ProductPhotoID { get; set; }
    public byte[] ThumbNailPhoto { get; set; }
    public string ThumbnailPhotoFileName { get; set; }
    public byte[] LargePhoto { get; set; }
    public string LargePhotoFileName { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductProductPhoto> ProductProductPhotoes { get; set; }
}

public partial class ProductProductPhoto
{
    public int ProductID { get; set; }
    public int ProductPhotoID { get; set; }
    public bool Primary { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
    public virtual ProductPhoto ProductPhoto { get; set; }
}

public partial class ProductReview
{
    public int ProductReviewID { get; set; }
    public int ProductID { get; set; }
    public string ReviewerName { get; set; }
    public System.DateTime ReviewDate { get; set; }
    public string EmailAddress { get; set; }
    public int Rating { get; set; }
    public string Comments { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
}

public partial class ProductSubcategory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ProductSubcategory()
    {
        this.Products = new HashSet<Product>();
    }

    public int ProductSubcategoryID { get; set; }
    public int ProductCategoryID { get; set; }
    public string Name { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
    public virtual ProductCategory ProductCategory { get; set; }
}

public partial class ProductVendor
{
    public int ProductID { get; set; }
    public int BusinessEntityID { get; set; }
    public int AverageLeadTime { get; set; }
    public decimal StandardPrice { get; set; }
    public Nullable<decimal> LastReceiptCost { get; set; }
    public Nullable<System.DateTime> LastReceiptDate { get; set; }
    public int MinOrderQty { get; set; }
    public int MaxOrderQty { get; set; }
    public Nullable<int> OnOrderQty { get; set; }
    public string UnitMeasureCode { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
    public virtual UnitMeasure UnitMeasure { get; set; }
    public virtual Vendor Vendor { get; set; }
}

public partial class PurchaseOrderDetail
{
    public int PurchaseOrderID { get; set; }
    public int PurchaseOrderDetailID { get; set; }
    public System.DateTime DueDate { get; set; }
    public short OrderQty { get; set; }
    public int ProductID { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal LineTotal { get; set; }
    public decimal ReceivedQty { get; set; }
    public decimal RejectedQty { get; set; }
    public decimal StockedQty { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
    public virtual PurchaseOrderHeader PurchaseOrderHeader { get; set; }
}

public partial class PurchaseOrderHeader
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public PurchaseOrderHeader()
    {
        this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
    }

    public int PurchaseOrderID { get; set; }
    public byte RevisionNumber { get; set; }
    public byte Status { get; set; }
    public int EmployeeID { get; set; }
    public int VendorID { get; set; }
    public int ShipMethodID { get; set; }
    public System.DateTime OrderDate { get; set; }
    public Nullable<System.DateTime> ShipDate { get; set; }
    public decimal SubTotal { get; set; }
    public decimal TaxAmt { get; set; }
    public decimal Freight { get; set; }
    public decimal TotalDue { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Employee Employee { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
    public virtual ShipMethod ShipMethod { get; set; }
    public virtual Vendor Vendor { get; set; }
}

public partial class SalesOrder_json
{
    public int SalesOrderID { get; set; }
    public byte RevisionNumber { get; set; }
    public System.DateTime OrderDate { get; set; }
    public System.DateTime DueDate { get; set; }
    public Nullable<System.DateTime> ShipDate { get; set; }
    public byte Status { get; set; }
    public bool OnlineOrderFlag { get; set; }
    public string SalesOrderNumber { get; set; }
    public string PurchaseOrderNumber { get; set; }
    public string AccountNumber { get; set; }
    public int CustomerID { get; set; }
    public Nullable<int> SalesPersonID { get; set; }
    public Nullable<int> TerritoryID { get; set; }
    public Nullable<int> BillToAddressID { get; set; }
    public Nullable<int> ShipToAddressID { get; set; }
    public Nullable<int> ShipMethodID { get; set; }
    public Nullable<int> CreditCardID { get; set; }
    public string CreditCardApprovalCode { get; set; }
    public Nullable<int> CurrencyRateID { get; set; }
    public decimal SubTotal { get; set; }
    public decimal TaxAmt { get; set; }
    public decimal Freight { get; set; }
    public decimal TotalDue { get; set; }
    public string Comment { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }
}

public partial class SalesOrderDetail
{
    public int SalesOrderID { get; set; }
    public int SalesOrderDetailID { get; set; }
    public string CarrierTrackingNumber { get; set; }
    public short OrderQty { get; set; }
    public int ProductID { get; set; }
    public int SpecialOfferID { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal UnitPriceDiscount { get; set; }
    public decimal LineTotal { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual SalesOrderHeader SalesOrderHeader { get; set; }
    public virtual SpecialOfferProduct SpecialOfferProduct { get; set; }
}

public partial class SalesOrderDetail_inmem
{
    public int SalesOrderID { get; set; }
    public long SalesOrderDetailID { get; set; }
    public string CarrierTrackingNumber { get; set; }
    public short OrderQty { get; set; }
    public int ProductID { get; set; }
    public int SpecialOfferID { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal UnitPriceDiscount { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual SalesOrderHeader_inmem SalesOrderHeader_inmem { get; set; }
    public virtual SpecialOfferProduct_inmem SpecialOfferProduct_inmem { get; set; }
}

public partial class SalesOrderDetail_ondisk
{
    public int SalesOrderID { get; set; }
    public long SalesOrderDetailID { get; set; }
    public string CarrierTrackingNumber { get; set; }
    public short OrderQty { get; set; }
    public int ProductID { get; set; }
    public int SpecialOfferID { get; set; }
    public decimal UnitPrice { get; set; }
    public decimal UnitPriceDiscount { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual SalesOrderHeader_ondisk SalesOrderHeader_ondisk { get; set; }
    public virtual SpecialOfferProduct_ondisk SpecialOfferProduct_ondisk { get; set; }
}

public partial class SalesOrderHeader
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SalesOrderHeader()
    {
        this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
        this.SalesOrderHeaderSalesReasons = new HashSet<SalesOrderHeaderSalesReason>();
    }

    public int SalesOrderID { get; set; }
    public byte RevisionNumber { get; set; }
    public System.DateTime OrderDate { get; set; }
    public System.DateTime DueDate { get; set; }
    public Nullable<System.DateTime> ShipDate { get; set; }
    public byte Status { get; set; }
    public bool OnlineOrderFlag { get; set; }
    public string SalesOrderNumber { get; set; }
    public string PurchaseOrderNumber { get; set; }
    public string AccountNumber { get; set; }
    public int CustomerID { get; set; }
    public Nullable<int> SalesPersonID { get; set; }
    public Nullable<int> TerritoryID { get; set; }
    public int BillToAddressID { get; set; }
    public int ShipToAddressID { get; set; }
    public int ShipMethodID { get; set; }
    public Nullable<int> CreditCardID { get; set; }
    public string CreditCardApprovalCode { get; set; }
    public Nullable<int> CurrencyRateID { get; set; }
    public decimal SubTotal { get; set; }
    public decimal TaxAmt { get; set; }
    public decimal Freight { get; set; }
    public decimal TotalDue { get; set; }
    public string Comment { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Address Address { get; set; }
    public virtual Address Address1 { get; set; }
    public virtual ShipMethod ShipMethod { get; set; }
    public virtual CreditCard CreditCard { get; set; }
    public virtual CurrencyRate CurrencyRate { get; set; }
    public virtual Customer Customer { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
    public virtual SalesPerson SalesPerson { get; set; }
    public virtual SalesTerritory SalesTerritory { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReasons { get; set; }
}

public partial class SalesOrderHeader_inmem
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SalesOrderHeader_inmem()
    {
        this.SalesOrderDetail_inmem = new HashSet<SalesOrderDetail_inmem>();
    }

    public int SalesOrderID { get; set; }
    public byte RevisionNumber { get; set; }
    public System.DateTime OrderDate { get; set; }
    public System.DateTime DueDate { get; set; }
    public Nullable<System.DateTime> ShipDate { get; set; }
    public byte Status { get; set; }
    public bool OnlineOrderFlag { get; set; }
    public string PurchaseOrderNumber { get; set; }
    public string AccountNumber { get; set; }
    public int CustomerID { get; set; }
    public int SalesPersonID { get; set; }
    public Nullable<int> TerritoryID { get; set; }
    public int BillToAddressID { get; set; }
    public int ShipToAddressID { get; set; }
    public int ShipMethodID { get; set; }
    public Nullable<int> CreditCardID { get; set; }
    public string CreditCardApprovalCode { get; set; }
    public Nullable<int> CurrencyRateID { get; set; }
    public decimal SubTotal { get; set; }
    public decimal TaxAmt { get; set; }
    public decimal Freight { get; set; }
    public string Comment { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderDetail_inmem> SalesOrderDetail_inmem { get; set; }
}

public partial class SalesOrderHeader_ondisk
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SalesOrderHeader_ondisk()
    {
        this.SalesOrderDetail_ondisk = new HashSet<SalesOrderDetail_ondisk>();
    }

    public int SalesOrderID { get; set; }
    public byte RevisionNumber { get; set; }
    public System.DateTime OrderDate { get; set; }
    public System.DateTime DueDate { get; set; }
    public Nullable<System.DateTime> ShipDate { get; set; }
    public byte Status { get; set; }
    public bool OnlineOrderFlag { get; set; }
    public string PurchaseOrderNumber { get; set; }
    public string AccountNumber { get; set; }
    public int CustomerID { get; set; }
    public int SalesPersonID { get; set; }
    public Nullable<int> TerritoryID { get; set; }
    public int BillToAddressID { get; set; }
    public int ShipToAddressID { get; set; }
    public int ShipMethodID { get; set; }
    public Nullable<int> CreditCardID { get; set; }
    public string CreditCardApprovalCode { get; set; }
    public Nullable<int> CurrencyRateID { get; set; }
    public decimal SubTotal { get; set; }
    public decimal TaxAmt { get; set; }
    public decimal Freight { get; set; }
    public string Comment { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderDetail_ondisk> SalesOrderDetail_ondisk { get; set; }
}

public partial class SalesOrderHeaderSalesReason
{
    public int SalesOrderID { get; set; }
    public int SalesReasonID { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual SalesOrderHeader SalesOrderHeader { get; set; }
    public virtual SalesReason SalesReason { get; set; }
}

public partial class SalesPerson
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SalesPerson()
    {
        this.SalesOrderHeaders = new HashSet<SalesOrderHeader>();
        this.SalesPersonQuotaHistories = new HashSet<SalesPersonQuotaHistory>();
        this.SalesTerritoryHistories = new HashSet<SalesTerritoryHistory>();
        this.Stores = new HashSet<Store>();
    }

    public int BusinessEntityID { get; set; }
    public Nullable<int> TerritoryID { get; set; }
    public Nullable<decimal> SalesQuota { get; set; }
    public decimal Bonus { get; set; }
    public decimal CommissionPct { get; set; }
    public decimal SalesYTD { get; set; }
    public decimal SalesLastYear { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Employee Employee { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
    public virtual SalesTerritory SalesTerritory { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesPersonQuotaHistory> SalesPersonQuotaHistories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesTerritoryHistory> SalesTerritoryHistories { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Store> Stores { get; set; }
}

public partial class SalesPersonQuotaHistory
{
    public int BusinessEntityID { get; set; }
    public System.DateTime QuotaDate { get; set; }
    public decimal SalesQuota { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual SalesPerson SalesPerson { get; set; }
}

public partial class SalesReason
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SalesReason()
    {
        this.SalesOrderHeaderSalesReasons = new HashSet<SalesOrderHeaderSalesReason>();
    }

    public int SalesReasonID { get; set; }
    public string Name { get; set; }
    public string ReasonType { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderHeaderSalesReason> SalesOrderHeaderSalesReasons { get; set; }
}

public partial class SalesTaxRate
{
    public int SalesTaxRateID { get; set; }
    public int StateProvinceID { get; set; }
    public byte TaxType { get; set; }
    public decimal TaxRate { get; set; }
    public string Name { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual StateProvince StateProvince { get; set; }
}

public partial class SalesTerritory
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SalesTerritory()
    {
        this.StateProvinces = new HashSet<StateProvince>();
        this.Customers = new HashSet<Customer>();
        this.SalesOrderHeaders = new HashSet<SalesOrderHeader>();
        this.SalesPersons = new HashSet<SalesPerson>();
        this.SalesTerritoryHistories = new HashSet<SalesTerritoryHistory>();
    }

    public int TerritoryID { get; set; }
    public string Name { get; set; }
    public string CountryRegionCode { get; set; }
    public string Group { get; set; }
    public decimal SalesYTD { get; set; }
    public decimal SalesLastYear { get; set; }
    public decimal CostYTD { get; set; }
    public decimal CostLastYear { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual CountryRegion CountryRegion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<StateProvince> StateProvinces { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Customer> Customers { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesPerson> SalesPersons { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesTerritoryHistory> SalesTerritoryHistories { get; set; }
}

public partial class SalesTerritoryHistory
{
    public int BusinessEntityID { get; set; }
    public int TerritoryID { get; set; }
    public System.DateTime StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual SalesPerson SalesPerson { get; set; }
    public virtual SalesTerritory SalesTerritory { get; set; }
}

public partial class ScrapReason
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ScrapReason()
    {
        this.WorkOrders = new HashSet<WorkOrder>();
    }

    public short ScrapReasonID { get; set; }
    public string Name { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<WorkOrder> WorkOrders { get; set; }
}

public partial class Shift
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Shift()
    {
        this.EmployeeDepartmentHistories = new HashSet<EmployeeDepartmentHistory>();
    }

    public byte ShiftID { get; set; }
    public string Name { get; set; }
    public System.TimeSpan StartTime { get; set; }
    public System.TimeSpan EndTime { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EmployeeDepartmentHistory> EmployeeDepartmentHistories { get; set; }
}

public partial class ShipMethod
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ShipMethod()
    {
        this.PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
        this.SalesOrderHeaders = new HashSet<SalesOrderHeader>();
    }

    public int ShipMethodID { get; set; }
    public string Name { get; set; }
    public decimal ShipBase { get; set; }
    public decimal ShipRate { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderHeader> SalesOrderHeaders { get; set; }
}

public partial class ShoppingCartItem
{
    public int ShoppingCartItemID { get; set; }
    public string ShoppingCartID { get; set; }
    public int Quantity { get; set; }
    public int ProductID { get; set; }
    public System.DateTime DateCreated { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
}

public partial class SpecialOffer
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SpecialOffer()
    {
        this.SpecialOfferProducts = new HashSet<SpecialOfferProduct>();
    }

    public int SpecialOfferID { get; set; }
    public string Description { get; set; }
    public decimal DiscountPct { get; set; }
    public string Type { get; set; }
    public string Category { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }
    public int MinQty { get; set; }
    public Nullable<int> MaxQty { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SpecialOfferProduct> SpecialOfferProducts { get; set; }
}

public partial class SpecialOffer_inmem
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SpecialOffer_inmem()
    {
        this.SpecialOfferProduct_inmem = new HashSet<SpecialOfferProduct_inmem>();
    }

    public int SpecialOfferID { get; set; }
    public string Description { get; set; }
    public decimal DiscountPct { get; set; }
    public string Type { get; set; }
    public string Category { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }
    public int MinQty { get; set; }
    public Nullable<int> MaxQty { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SpecialOfferProduct_inmem> SpecialOfferProduct_inmem { get; set; }
}

public partial class SpecialOffer_ondisk
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SpecialOffer_ondisk()
    {
        this.SpecialOfferProduct_ondisk = new HashSet<SpecialOfferProduct_ondisk>();
    }

    public int SpecialOfferID { get; set; }
    public string Description { get; set; }
    public decimal DiscountPct { get; set; }
    public string Type { get; set; }
    public string Category { get; set; }
    public System.DateTime StartDate { get; set; }
    public System.DateTime EndDate { get; set; }
    public int MinQty { get; set; }
    public Nullable<int> MaxQty { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SpecialOfferProduct_ondisk> SpecialOfferProduct_ondisk { get; set; }
}

public partial class SpecialOfferProduct
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SpecialOfferProduct()
    {
        this.SalesOrderDetails = new HashSet<SalesOrderDetail>();
    }

    public int SpecialOfferID { get; set; }
    public int ProductID { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }
    public virtual SpecialOffer SpecialOffer { get; set; }
}

public partial class SpecialOfferProduct_inmem
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SpecialOfferProduct_inmem()
    {
        this.SalesOrderDetail_inmem = new HashSet<SalesOrderDetail_inmem>();
    }

    public int SpecialOfferID { get; set; }
    public int ProductID { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product_inmem Product_inmem { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderDetail_inmem> SalesOrderDetail_inmem { get; set; }
    public virtual SpecialOffer_inmem SpecialOffer_inmem { get; set; }
}

public partial class SpecialOfferProduct_ondisk
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public SpecialOfferProduct_ondisk()
    {
        this.SalesOrderDetail_ondisk = new HashSet<SalesOrderDetail_ondisk>();
    }

    public int SpecialOfferID { get; set; }
    public int ProductID { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product_ondisk Product_ondisk { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesOrderDetail_ondisk> SalesOrderDetail_ondisk { get; set; }
    public virtual SpecialOffer_ondisk SpecialOffer_ondisk { get; set; }
}

public partial class StateProvince
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public StateProvince()
    {
        this.Addresses = new HashSet<Address>();
        this.SalesTaxRates = new HashSet<SalesTaxRate>();
    }

    public int StateProvinceID { get; set; }
    public string StateProvinceCode { get; set; }
    public string CountryRegionCode { get; set; }
    public bool IsOnlyStateProvinceFlag { get; set; }
    public string Name { get; set; }
    public int TerritoryID { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Address> Addresses { get; set; }
    public virtual CountryRegion CountryRegion { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<SalesTaxRate> SalesTaxRates { get; set; }
    public virtual SalesTerritory SalesTerritory { get; set; }
}

public partial class Store
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Store()
    {
        this.Customers = new HashSet<Customer>();
    }

    public int BusinessEntityID { get; set; }
    public string Name { get; set; }
    public Nullable<int> SalesPersonID { get; set; }
    public string Demographics { get; set; }
    public System.Guid rowguid { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual BusinessEntity BusinessEntity { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Customer> Customers { get; set; }
    public virtual SalesPerson SalesPerson { get; set; }
}

public partial class TrackingEvent
{
    public int TrackingEventID { get; set; }
    public string EventName { get; set; }
}

public partial class TransactionHistory
{
    public int TransactionID { get; set; }
    public int ProductID { get; set; }
    public int ReferenceOrderID { get; set; }
    public int ReferenceOrderLineID { get; set; }
    public System.DateTime TransactionDate { get; set; }
    public string TransactionType { get; set; }
    public int Quantity { get; set; }
    public decimal ActualCost { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
}

public partial class TransactionHistoryArchive
{
    public int TransactionID { get; set; }
    public int ProductID { get; set; }
    public int ReferenceOrderID { get; set; }
    public int ReferenceOrderLineID { get; set; }
    public System.DateTime TransactionDate { get; set; }
    public string TransactionType { get; set; }
    public int Quantity { get; set; }
    public decimal ActualCost { get; set; }
    public System.DateTime ModifiedDate { get; set; }
}

public partial class UnitMeasure
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UnitMeasure()
    {
        this.BillOfMaterials = new HashSet<BillOfMaterial>();
        this.Products = new HashSet<Product>();
        this.Products1 = new HashSet<Product>();
        this.ProductVendors = new HashSet<ProductVendor>();
    }

    public string UnitMeasureCode { get; set; }
    public string Name { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<BillOfMaterial> BillOfMaterials { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Product> Products1 { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductVendor> ProductVendors { get; set; }
}

public partial class Vendor
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Vendor()
    {
        this.ProductVendors = new HashSet<ProductVendor>();
        this.PurchaseOrderHeaders = new HashSet<PurchaseOrderHeader>();
    }

    public int BusinessEntityID { get; set; }
    public string AccountNumber { get; set; }
    public string Name { get; set; }
    public byte CreditRating { get; set; }
    public bool PreferredVendorStatus { get; set; }
    public bool ActiveFlag { get; set; }
    public string PurchasingWebServiceURL { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual BusinessEntity BusinessEntity { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ProductVendor> ProductVendors { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PurchaseOrderHeader> PurchaseOrderHeaders { get; set; }
}

public partial class WorkOrder
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public WorkOrder()
    {
        this.WorkOrderRoutings = new HashSet<WorkOrderRouting>();
    }

    public int WorkOrderID { get; set; }
    public int ProductID { get; set; }
    public int OrderQty { get; set; }
    public int StockedQty { get; set; }
    public short ScrappedQty { get; set; }
    public System.DateTime StartDate { get; set; }
    public Nullable<System.DateTime> EndDate { get; set; }
    public System.DateTime DueDate { get; set; }
    public Nullable<short> ScrapReasonID { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Product Product { get; set; }
    public virtual ScrapReason ScrapReason { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<WorkOrderRouting> WorkOrderRoutings { get; set; }
}

public partial class WorkOrderRouting
{
    public int WorkOrderID { get; set; }
    public int ProductID { get; set; }
    public short OperationSequence { get; set; }
    public short LocationID { get; set; }
    public System.DateTime ScheduledStartDate { get; set; }
    public System.DateTime ScheduledEndDate { get; set; }
    public Nullable<System.DateTime> ActualStartDate { get; set; }
    public Nullable<System.DateTime> ActualEndDate { get; set; }
    public Nullable<decimal> ActualResourceHrs { get; set; }
    public decimal PlannedCost { get; set; }
    public Nullable<decimal> ActualCost { get; set; }
    public System.DateTime ModifiedDate { get; set; }

    public virtual Location Location { get; set; }
    public virtual WorkOrder WorkOrder { get; set; }
}
